name: Test Suite

on:
    push:
        branches: ["master"]
    pull_request:
        branches: ["master"]

jobs:
    linters:
        runs-on: ubuntu-latest
        timeout-minutes: 5
        strategy:
            matrix:
                python-version: ["3.8", "3.9", "3.10"]

        steps:
            - uses: actions/checkout@v3
            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v4
              with:
                  python-version: ${{ matrix.python-version }}
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements/dev-requirements.txt
                  pip install -r requirements/test-requirements.txt
            - name: Lint
              run: ./scripts/lint.sh

    unittests:
        runs-on: ubuntu-latest
        timeout-minutes: 30
        strategy:
            matrix:
                python-version: ["3.8", "3.9", "3.10"]

        steps:
            - uses: actions/checkout@v3
            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v4
              with:
                  python-version: ${{ matrix.python-version }}
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements/test-requirements.txt
            - name: Run unittests
              run: ./scripts/run-tests.sh
